

#
# This file is autogenerated during plugin_quickstart and overwritten during
# plugin_makedist. DO NOT CHANGE IT if you plan to use plugin_makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Kennth T. Moore',
 'author_email': 'kenneth-t-moore-1@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO component wrapper for PDCYL',
 'download_url': '',
 'entry_points': '[openmdao.component]\npdcyl_comp.pdcyl_comp.PdcylComp=pdcyl_comp.pdcyl_comp:PdcylComp',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Kennth T. Moore',
 'maintainer_email': 'kenneth.t.moore-1@nasa.gov',
 'name': 'pdcyl_comp',
 'package_data': {'pdcyl_comp': ['sphinx_build/html/usage.html',
                                 'sphinx_build/html/py-modindex.html',
                                 'sphinx_build/html/genindex.html',
                                 'sphinx_build/html/search.html',
                                 'sphinx_build/html/srcdocs.html',
                                 'sphinx_build/html/index.html',
                                 'sphinx_build/html/objects.inv',
                                 'sphinx_build/html/searchindex.js',
                                 'sphinx_build/html/.buildinfo',
                                 'sphinx_build/html/pkgdocs.html',
                                 'sphinx_build/html/_sources/pkgdocs.txt',
                                 'sphinx_build/html/_sources/srcdocs.txt',
                                 'sphinx_build/html/_sources/index.txt',
                                 'sphinx_build/html/_sources/usage.txt',
                                 'sphinx_build/html/_modules/index.html',
                                 'sphinx_build/html/_modules/pdcyl_comp/pdcyl_comp.html',
                                 'sphinx_build/html/_static/underscore.js',
                                 'sphinx_build/html/_static/pygments.css',
                                 'sphinx_build/html/_static/basic.css',
                                 'sphinx_build/html/_static/file.png',
                                 'sphinx_build/html/_static/sidebar.js',
                                 'sphinx_build/html/_static/jquery.js',
                                 'sphinx_build/html/_static/default.css',
                                 'sphinx_build/html/_static/minus.png',
                                 'sphinx_build/html/_static/doctools.js',
                                 'sphinx_build/html/_static/searchtools.js',
                                 'sphinx_build/html/_static/plus.png',
                                 'test/PDCYL.in',
                                 'test/transport.dump',
                                 'test/transport.in',
                                 'test/test_pdcyl_comp.py',
                                 'test/pdcyl.dump',
                                 'test/transport.out',
                                 'test/PDCYL.out']},
 'package_dir': {'': 'src'},
 'packages': ['pdcyl_comp'],
 'url': 'https://github.com/OpenMDAO-Plugins/pdcyl_comp',
 'version': '0.2',
 'zip_safe': False}


setup(**kwargs)

