#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Kennth T. Moore',
 'author_email': 'kenneth-t-moore-1@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO component wrapper for PDCYL',
 'download_url': '',
 'entry_points': '[openmdao.component]\npdcyl_comp.pdcyl_comp.PdcylComp=pdcyl_comp.pdcyl_comp:PdcylComp\n\n[openmdao.container]\npdcyl_comp.pdcyl_comp.PdcylComp=pdcyl_comp.pdcyl_comp:PdcylComp',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Kennth T. Moore',
 'maintainer_email': 'kenneth.t.moore-1@nasa.gov',
 'name': 'pdcyl_comp',
 'package_data': {'pdcyl_comp': []},
 'package_dir': {'': 'src'},
 'packages': ['pdcyl_comp'],
 'url': 'https://github.com/OpenMDAO-Plugins/pdcyl_comp',
 'version': '0.4',
 'zip_safe': False}


setup(**kwargs)

